theme: jekyll-theme-minima

title: bbroot App Support
description: Technical support pages for bbroot apps
baseurl: ""
url: "https://app.404w.com"

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
